---
- name: Ensure Credentials Directory Exists
  ansible.builtin.file:
    path: "{{ wordpress_credentials_save_path }}"
    state: directory
    mode: "0700"
  delegate_to: localhost
  become: false

- name: Save WordPress Credentials
  ansible.builtin.template:
    src: credentials.yml.j2
    dest: "{{ wordpress_credentials_save_path }}/{{ wordpress_domain }}.yml"
    mode: "0600"
  delegate_to: localhost
  become: false
