---
- name: Install EPEL Repository
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install Remi Repository
  ansible.builtin.dnf:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_facts['distribution_major_version'] }}.rpm"
    state: present
    disable_gpg_check: true

- name: Reset PHP Module
  ansible.builtin.command:
    cmd: "dnf module reset php -y"
  register: wordpress_php_module_reset
  changed_when: "'Resetting' in wordpress_php_module_reset.stdout"

- name: Enable Remi PHP Module
  ansible.builtin.command:
    cmd: "dnf module enable php:remi-{{ wordpress_php_version }} -y"
  register: wordpress_remi_module
  changed_when: "'Enabling' in wordpress_remi_module.stdout"
