---
- name: Install EPEL Repository
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install Remi Repository
  ansible.builtin.dnf:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_facts['distribution_major_version'] }}.rpm"
    state: present
    disable_gpg_check: true

- name: Check Current PHP Module Stream
  ansible.builtin.command:
    cmd: "dnf module list --enabled php"
  register: wordpress_php_module_status
  changed_when: false
  failed_when: false

- name: Reset PHP Module
  ansible.builtin.command:
    cmd: "dnf module reset php -y"
  when: >
    wordpress_php_module_status.rc == 0 and
    'remi-' ~ wordpress_php_version not in wordpress_php_module_status.stdout
  changed_when: true

- name: Enable Remi PHP Module
  ansible.builtin.command:
    cmd: "dnf module enable php:remi-{{ wordpress_php_version }} -y"
  when: >
    wordpress_php_module_status.rc != 0 or
    'remi-' ~ wordpress_php_version not in wordpress_php_module_status.stdout
  changed_when: true
