---
dependency:
  name: shell
  command: |
    ansible-galaxy role install -r meta/install_requirements.yml -p ./roles --force
    ansible-galaxy collection install -r meta/install_requirements.yml -p ./collections --force
driver:
  name: docker
platforms:
  - name: almalinux-10
    image: ghcr.io/ginanck/molecule-almalinux:10-latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles:../../../
    ANSIBLE_COLLECTIONS_PATH: ../../collections
  inventory:
    host_vars:
      almalinux-10:
        ansible_user: root
        wordpress_domain: "example.com"
        wordpress_db_host: "localhost"
        wordpress_db_name: "wordpress"
        wordpress_db_user: "wordpress"
        wordpress_db_password: "test_password"
        wordpress_admin_password: "test_admin_password"
        mariadb_root_password: "molecule_test_password"
        mariadb_databases:
          - name: wordpress
        mariadb_users:
          - name: wordpress
            password: "test_password"
            host: "localhost"
            priv: "wordpress.*:ALL"
        mariadb_credentials_save_enabled: false
        nginx_sysctl_parameters: []
        wordpress_credentials_save_enabled: false
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
verifier:
  name: ansible
  options:
    playbook: ../resources/verify.yml
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
